# Copyright 2025-2026 MicroEJ Corp. All rights reserved.
# MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.

# The name of the package.
systemProp.package.module.name=my-package

# The group name for the package.
systemProp.package.group.name=com.mycompany

# The version for the package.
systemProp.package.version=1.0.0-RC

# Whether to enable the Application Developer Mode in the packaging project.
# When building a Feature, the Kernel is loaded from prebuilt files bundled with the package, not from the project sources.
# This mode is disabled by default in the packaging project, but is enabled by default for the end-user of the package.
systemProp.app.developer.mode.enabled=false
