/*
 * Java
 *
 * Copyright 2025 MicroEJ Corp. All rights reserved.
 * MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.microej.example.app;

/**
 * Generated by the application template.
 *
 * Please keep it in sync with the property 'applicationEntryPoint' defined in build.gradle.kts.
 */
public class Main {

	public static void main(String[] args) {
		System.out.println("Hello World!"); //$NON-NLS-1$
	}
}