# Copyright 2026 MicroEJ Corp. All rights reserved.
# MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.

# Whether to enable the Application Developer Mode (enabled by default).
# When building a Feature, the Kernel is loaded from prebuilt files bundled with the package, not from the project sources.
#systemProp.app.developer.mode.enabled=false

# Selects the kernel for application builds.
# Used by the microej-app-conventions plugin to resolve the kernel project and prebuilt binaries.
#systemProp.kernel.name=